### ISSUE TITLE
Could not build wheels for lxml, Pillow, reportlab

### ISSUE THREAD

**Issue by UjwalTR** [o-richard/TimetableGenerator#3]
![error 3](https://github.com/o-richard/TimetableGenerator/assets/69851376/a3150cde-23ba-4bf5-b80e-9949d3828216)
please help me with this

**Comment by UjwalTR** [comment]
lxml , pillow , reportlab in not installing

**Comment by UjwalTR** [comment]
i got the solution 
while installing lxml , pillow , reportlab
remove the specific version numbers in the the text file requirements.txt 
u r good to go

**Comment by o-richard** [comment]
In requirements.txt, I specified the package versions that I used while developing the project.
In runtime.txt, I specified the python version that I used while developing the project.

I haven't updated the codebase to support the latest versions of the different packages.
